### ISSUE TITLE
can't display

### ISSUE THREAD

**Issue by songxinqu** [magmaOffenburg/RoboViz#125]
**After executing./build.sh and returning success：**
parallels@dd:~/RoboViz/scripts$ ./build.sh

BUILD SUCCESSFUL in 8s
8 actionable tasks: 6 executed, 2 up-to-date

BUILD SUCCESSFUL in 383ms
2 actionable tasks: 2 executed
parallels@dd:~/RoboViz/scripts$

parallels@dd:~/RoboViz/scripts$ ./build.sh

**I went into the bin folder and executed Roboviz.sh, but after executing, no platform appeared and nothing was displayed.
Here is the result:**
parallels@dd:~/RoboViz-master/bin$ ./roboviz.sh
Exception in thread "AWT-EventQueue-1" java.lang.UnsatisfiedLinkError: Can&apos;t load library: /home/parallels/RoboViz-master/bin/natives/linux-aarch64//libgluegen-rt.so
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1820)
        at java.lang.Runtime.load0(Runtime.java:810)
        at java.lang.System.load(System.java:1088)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:624)
        at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:63)
        at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:106)
        at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:487)
        at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:421)
        at com.jogamp.common.os.Platform$1.run(Platform.java:317)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
        at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:147)
        at org.magmaoffenburg.roboviz.gui.MainWindow.initializeGLCanvas(MainWindow.kt:128)
        at org.magmaoffenburg.roboviz.gui.MainWindow.<init>(MainWindow.kt:46)
        at org.magmaoffenburg.roboviz.MainKt.createAndShowGUI(Main.kt:51)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:705)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
parallels@dd:~/RoboViz-master/bin$ ^C

**Ubuntu 20.04.3 LTS
arm架构
OStype：64bit
Gnome version:3.36.8
windowing system:x11
Roboviz-master the latest version**

**Comment by ancientScholars** [comment]
I was having problem with manjaro , I use `MESA_LOADER_DRIVER_OVERRIDE=i965 ./roboviz.sh`  and the graph is displayed. Hope this helps you.

**Comment by alaa7alnajjar** [comment]
I had the same problem. I can confirm, @HLYTQ solution works
