### ISSUE TITLE
Exception when starting roboviz on Mac

### ISSUE THREAD

**Issue by pmacalpine** [magmaOffenburg/RoboViz#93]
I recently started using a new Mac and when I tried to run roboviz on it I get the exception below.  I've tried this with both Java 7 and Java 8 JDK/JRE, as well as versions of roboviz back to 1.1.0, and get the same error.  Has roboviz been tested that it works on a Mac with Java 7 or 8?  Previously I was using roboviz on an older mac with a version of roboviz that was modified to work with Java 6.  

Exception in thread "Timer-0" java.lang.RuntimeException: Unable to initialize JAWT
    at jogamp.nativewindow.jawt.JAWT$1.run(JAWT.java:103)
    at java.security.AccessController.doPrivileged(Native Method)
    at jogamp.nativewindow.jawt.JAWT.getJAWT(JAWT.java:98)
    at jogamp.nativewindow.jawt.macosx.MacOSXJAWTWindow.lockSurfaceImpl(MacOSXJAWTWindow.java:68)
    at jogamp.nativewindow.jawt.JAWTWindow.lockSurface(JAWTWindow.java:123)
    at jogamp.opengl.GLDrawableImpl.lockSurface(GLDrawableImpl.java:187)
    at jogamp.opengl.GLDrawableImpl.setRealized(GLDrawableImpl.java:148)
    at javax.media.opengl.awt.GLCanvas.validateGLDrawable(GLCanvas.java:559)
    at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:382)
    at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:74)
    at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:140)
    at com.jogamp.opengl.util.FPSAnimator$1.run(FPSAnimator.java:125)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)

**Comment by Gama11** [comment]
I don't have a Mac, so I've never tested RoboViz on it.

**Comment by Gama11** [comment]
Did you ever manage to solve this? Does your branch for Java 6 solve this?

We have a team member that has the same issue.

**Comment by pmacalpine** [comment]
It looks like Java AWT won't work on Mac OS X for versions of Java 7 and higher.  My somewhat outdated version of roboviz for java 6 will work, but only assuming you are running java 6.  I think the following link gives some more insight into the issue. https://github.com/caprica/vlcj/issues/205.
