### ISSUE TITLE
Handle -nan Strings

### ISSUE THREAD

**Issue by Gama11** [magmaOffenburg/RoboViz#99]
When an agent explodes because of the toe movement bug, RoboViz crashes with the following:

```
Exception in thread "Thread-40" java.lang.NumberFormatException: For input string: "-nan"
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at rv.comm.rcssserver.scenegraph.TransformNode.setMatrix(TransformNode.java:50)
        at rv.comm.rcssserver.scenegraph.TransformNode.update(TransformNode.java:59)
        at rv.comm.rcssserver.scenegraph.Node.update(Node.java:101)
        at rv.comm.rcssserver.scenegraph.TransformNode.update(TransformNode.java:61)
        at rv.comm.rcssserver.scenegraph.Node.update(Node.java:101)
        at rv.comm.rcssserver.scenegraph.SceneGraph.update(SceneGraph.java:196)
        at rv.comm.rcssserver.MessageParser.parse(MessageParser.java:59)
        at rv.comm.rcssserver.ServerComm$MessageReceiver.run(ServerComm.java:67)
```

Although this is a server issue, RoboViz could be made more robust to ignore these exceptions.

**Comment by Gama11** [comment]
This was fixed a while ago.
